server:
  port: 7777
spring:
  application:
    name: itrip-biz-consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/