server:
  port: 10001
spring:
  application:
    name: itrip-search-provider
  main:
    allow-bean-definition-overriding: true
  data:
    solr:
      host: http://localhost:8080/solr/Itrip
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/